name: covid_qrcode_bfh
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  get: ^4.1.4
  google_sign_in: ^5.0.3
  pretty_qr_code: ^2.0.1
  provider: ^5.0.0
  qr_code_scanner: ^0.4.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/logo/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSansPro/SourceSansPro-Regular.ttf
          weight: 500
        - asset: assets/fonts/SourceSansPro/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro/SourceSansPro-Black.ttf
          weight: 800
    - family: ChelaOne
      fonts:
        - asset: assets/fonts/ChelaOne/ChelaOne-Regular.ttf